name: Build and deploy

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install Dependencies
        run: npm i 

      - name: Compile Sass to CSS
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Build to Pages
        id: deploy
        uses: actions/deploy-pages@v2
        with:
          # Path to the build directory
          path: './'
